// GENERATED by test_gen.py — expected values for fixture.safetensors.
#pragma once
#include <cstdint>
#include <array>
namespace fixture {
// w_f32: F32 [2x3]
inline constexpr std::array<float, 6> W_F32{ { 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f }};
inline constexpr std::size_t W_F32_RANK = 2;
inline constexpr std::size_t W_F32_SHAPE[2] = { 2, 3 };
// w_f16: F16 [2x2]
inline constexpr std::array<float, 4> W_F16{ { 1.5f, -2.0f, 0.25f, 4.0f }};
inline constexpr std::size_t W_F16_RANK = 2;
inline constexpr std::size_t W_F16_SHAPE[2] = { 2, 2 };
// w_bf16: BF16 [2x3]
inline constexpr std::array<float, 6> W_BF16{ { 1.0f, 2.0f, 3.0f, -1.0f, 0.5f, 4.0f }};
inline constexpr std::size_t W_BF16_RANK = 2;
inline constexpr std::size_t W_BF16_SHAPE[2] = { 2, 3 };
// idx_i64: I64 [3]
inline constexpr std::array<std::int64_t, 3> IDX_I64{ { 10, 20, 30 }};
inline constexpr std::size_t IDX_I64_RANK = 1;
inline constexpr std::size_t IDX_I64_SHAPE[1] = { 3 };
// m_i32: I32 [2x2]
inline constexpr std::array<std::int32_t, 4> M_I32{ { 1, -2, 3, -4 }};
inline constexpr std::size_t M_I32_RANK = 2;
inline constexpr std::size_t M_I32_SHAPE[2] = { 2, 2 };
// bytes_u8: U8 [4]
inline constexpr std::array<std::uint8_t, 4> BYTES_U8{ { 0, 127, 128, 255 }};
inline constexpr std::size_t BYTES_U8_RANK = 1;
inline constexpr std::size_t BYTES_U8_SHAPE[1] = { 4 };
// m_i8: I8 [2x2]
inline constexpr std::array<std::int8_t, 4> M_I8{ { -1, 2, -3, 4 }};
inline constexpr std::size_t M_I8_RANK = 2;
inline constexpr std::size_t M_I8_SHAPE[2] = { 2, 2 };
// mask_bool: BOOL [3]
inline constexpr std::array<bool, 3> MASK_BOOL{ { true, false, true }};
inline constexpr std::size_t MASK_BOOL_RANK = 1;
inline constexpr std::size_t MASK_BOOL_SHAPE[1] = { 3 };
}  // namespace fixture
