#include <algorithm>
#include <array>
#include <filesystem>
#include <string_view>

#include <catch2/catch_test_macros.hpp>

#include <model/safetensors.h>
#include <model/tensor.h>
#include <util/types.h>

#include "fixture_expected.h"

using namespace culpeo::inference;

namespace
{
    const std::filesystem::path fixture_path = std::filesystem::path{ FIXTURE_DIR } / "fixture.safetensors";

    model::safetensors load_fixture()
    {
        auto loaded = model::safetensors::load(fixture_path);
        REQUIRE(loaded.has_value());
        return std::move(*loaded);
    }

    // Compares an mdspan-backed matrix against the flat row-major expected
    // values generated by test_gen.py.
    template<typename Mat, typename T, std::size_t N>
    void check_matrix(const Mat & mat, const std::array<T, N> & expected, std::size_t rows, std::size_t cols)
    {
        REQUIRE(mat.extent(0) == rows);
        REQUIRE(mat.extent(1) == cols);
        for (std::size_t r = 0; r < rows; ++r)
        {
            for (std::size_t c = 0; c < cols; ++c)
            {
                INFO("row " << r << ", col " << c);
                CHECK(mat[r, c] == expected[r * cols + c]);
            }
        }
    }
}

TEST_CASE("safetensors::load succeeds and reports every fixture tensor", "[model][safetensors]")
{
    const auto model_file = load_fixture();

    REQUIRE(model_file.tensor_count() == 8);

    const auto keys = model_file.keys();
    for (auto name : { "w_f32", "w_f16", "w_bf16", "idx_i64", "m_i32", "bytes_u8", "m_i8", "mask_bool" })
    {
        CHECK(std::ranges::find(keys, std::string_view{ name }) != keys.end());
    }
}

TEST_CASE("safetensors::load fails for a missing file", "[model][safetensors]")
{
    const auto loaded = model::safetensors::load("/nonexistent/path/does-not-exist.safetensors");
    REQUIRE_FALSE(loaded.has_value());
}

TEST_CASE("get_tensor: unknown name fails", "[model][safetensors]")
{
    const auto model_file = load_fixture();
    const auto missing = model_file.get_tensor("not_a_real_tensor");
    REQUIRE_FALSE(missing.has_value());
}

TEST_CASE("F32 tensor is read and projected exactly", "[model][tensor][f32]")
{
    const auto model_file = load_fixture();
    const auto tensor = model_file.get_tensor("w_f32");
    REQUIRE(tensor.has_value());

    const auto mat = tensor->as_mat<util::data_type::F32>();
    REQUIRE(mat.has_value());
    check_matrix(*mat, fixture::W_F32, fixture::W_F32_SHAPE[0], fixture::W_F32_SHAPE[1]);
}

TEST_CASE("F16 tensor is read and widened to float exactly", "[model][tensor][f16]")
{
    const auto model_file = load_fixture();
    const auto tensor = model_file.get_tensor("w_f16");
    REQUIRE(tensor.has_value());

    const auto mat = tensor->as_mat<util::data_type::F16>();
    REQUIRE(mat.has_value());
    check_matrix(*mat, fixture::W_F16, fixture::W_F16_SHAPE[0], fixture::W_F16_SHAPE[1]);
}

TEST_CASE("BF16 tensor is read and widened to float exactly", "[model][tensor][bf16]")
{
    const auto model_file = load_fixture();
    const auto tensor = model_file.get_tensor("w_bf16");
    REQUIRE(tensor.has_value());

    const auto mat = tensor->as_mat<util::data_type::BF16>();
    REQUIRE(mat.has_value());
    check_matrix(*mat, fixture::W_BF16, fixture::W_BF16_SHAPE[0], fixture::W_BF16_SHAPE[1]);
}

TEST_CASE("I32 tensor is read and projected exactly", "[model][tensor][i32]")
{
    const auto model_file = load_fixture();
    const auto tensor = model_file.get_tensor("m_i32");
    REQUIRE(tensor.has_value());

    const auto mat = tensor->as_mat<util::data_type::I32>();
    REQUIRE(mat.has_value());
    check_matrix(*mat, fixture::M_I32, fixture::M_I32_SHAPE[0], fixture::M_I32_SHAPE[1]);
}

TEST_CASE("I8 tensor is read and projected exactly", "[model][tensor][i8]")
{
    const auto model_file = load_fixture();
    const auto tensor = model_file.get_tensor("m_i8");
    REQUIRE(tensor.has_value());

    const auto mat = tensor->as_mat<util::data_type::I8>();
    REQUIRE(mat.has_value());
    check_matrix(*mat, fixture::M_I8, fixture::M_I8_SHAPE[0], fixture::M_I8_SHAPE[1]);
}

TEST_CASE("as_mat rejects a dtype that does not match the tensor's stored dtype", "[model][tensor][errors]")
{
    const auto model_file = load_fixture();
    const auto tensor = model_file.get_tensor("w_f32");
    REQUIRE(tensor.has_value());

    // Fixture is F32; requesting I32 must fail rather than reinterpret bits.
    const auto mismatched = tensor->as_mat<util::data_type::I32>();
    REQUIRE_FALSE(mismatched.has_value());
}

TEST_CASE("as_mat rejects 1D tensors as non-matrices", "[model][tensor][errors]")
{
    const auto model_file = load_fixture();

    // idx_i64, bytes_u8 and mask_bool are all rank-1; as_mat<> only supports
    // rank-2 tensors, so each must fail without partially reinterpreting data.
    const auto idx = model_file.get_tensor("idx_i64");
    REQUIRE(idx.has_value());
    REQUIRE_FALSE(idx->as_mat<util::data_type::I64>().has_value());

    const auto bytes = model_file.get_tensor("bytes_u8");
    REQUIRE(bytes.has_value());
    REQUIRE_FALSE(bytes->as_mat<util::data_type::U8>().has_value());

    const auto mask = model_file.get_tensor("mask_bool");
    REQUIRE(mask.has_value());
    REQUIRE_FALSE(mask->as_mat<util::data_type::BOOL>().has_value());
}
