#!/usr/bin/env python3
"""Generate a tiny multi-dtype .safetensors fixture for loader tests.

Hand-rolls the container format ([u64 header_len][json header][raw blob])
so the test corpus has no build-time dependency on the Python safetensors
library, and emits a C++ header of expected values so the loader test is a
real differential check rather than a smoke test.

Values are chosen exact in every dtype (small ints, simple binary
fractions) so bf16/f16 conversion is lossless and the C++ side asserts
equality, not approximate. Cross-checked against the reference library by
tests/verify_fixture.py.

Regenerate:  python3 tools/gen_fixture.py
Outputs:     tests/fixture.safetensors, tests/fixture_expected.h
"""
import json
import struct
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent.parent / "tests"
OUT.mkdir(exist_ok=True)


def to_bf16_bits(arr_f32):
    # bf16 = top 16 bits of float32. Values here are exact in 7 mantissa
    # bits, so truncation equals round-to-nearest.
    u = arr_f32.astype(np.float32).view(np.uint32)
    return (u >> 16).astype(np.uint16)


# One tensor per dtype the loader's matrix<> trait supports. Tiny shapes;
# 2-D for the matmul-operand dtypes, 1-D for an index/norm-like vector.
tensors = {
    "w_f32":     ("F32",  np.array([[1, 2, 3], [4, 5, 6]], np.float32)),
    "w_f16":     ("F16",  np.array([[1.5, -2.0], [0.25, 4.0]], np.float16)),
    "w_bf16":    ("BF16", np.array([[1, 2, 3], [-1, 0.5, 4]], np.float32)),
    "idx_i64":   ("I64",  np.array([10, 20, 30], np.int64)),
    "m_i32":     ("I32",  np.array([[1, -2], [3, -4]], np.int32)),
    "bytes_u8":  ("U8",   np.array([0, 127, 128, 255], np.uint8)),
    "m_i8":      ("I8",   np.array([[-1, 2], [-3, 4]], np.int8)),
    "mask_bool": ("BOOL", np.array([True, False, True], np.bool_)),
}


def raw_bytes(dtype, arr):
    if dtype == "BF16":
        return to_bf16_bits(arr).tobytes()
    if dtype == "BOOL":
        return arr.astype(np.uint8).tobytes()  # 1 byte/bool per spec
    return arr.tobytes()


def build(tensors):
    blob = b""
    header = {}
    for name, (dtype, arr) in tensors.items():
        data = raw_bytes(dtype, arr)
        start = len(blob)
        blob += data
        header[name] = {"dtype": dtype, "shape": list(arr.shape),
                        "data_offsets": [start, start + len(data)]}
    hjson = json.dumps(header, separators=(",", ":")).encode()
    hjson += b" " * ((-len(hjson)) % 8)          # 8-byte align, space pad
    return struct.pack("<Q", len(hjson)) + hjson + blob


data = build(tensors)
(OUT / "fixture.safetensors").write_bytes(data)
print(f"wrote tests/fixture.safetensors: {len(data)} bytes, {len(tensors)} tensors")


def cpp_ctype(dtype):
    return {"F32": "float", "F16": "float", "BF16": "float", "BOOL": "bool",
            "I8": "std::int8_t", "U8": "std::uint8_t", "I16": "std::int16_t",
            "I32": "std::int32_t", "I64": "std::int64_t"}[dtype]


def _flit(v):
    s = f"{float(v):.9g}"
    if "." not in s and "e" not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f"


def cpp_vals(dtype, arr):
    flat = arr.flatten()
    if dtype in ("F32", "F16", "BF16"):
        return ", ".join(_flit(v) for v in flat.astype(np.float32))
    if dtype == "BOOL":
        return ", ".join("true" if v else "false" for v in flat)
    return ", ".join(str(int(v)) for v in flat)


lines = [f"// GENERATED by {Path(__file__).name} — expected values for "
         "fixture.safetensors.",
         "#pragma once", "#include <cstdint>", "#include <array>", "namespace fixture {"]
for name, (dtype, arr) in tensors.items():
    c = name.upper()
    shape = "x".join(map(str, arr.shape)) or "scalar"
    lines.append(f"// {name}: {dtype} [{shape}]")
    lines.append(f"inline constexpr std::array<{cpp_ctype(dtype)}, {arr.size}> {c}{{ "
                 f"{{ {cpp_vals(dtype, arr)} }}}};")
    lines.append(f"inline constexpr std::size_t {c}_RANK = {arr.ndim};")
    dims = ", ".join(map(str, arr.shape))
    lines.append(f"inline constexpr std::size_t {c}_SHAPE[{arr.ndim}] = "
                 f"{{ {dims} }};")
(OUT / "fixture_expected.h").write_text("\n".join(lines) + "\n}  // namespace fixture\n")
print("wrote tests/fixture_expected.h")