#!/usr/bin/env python3
"""Generate golden test vectors for the infer kernel library.

Reference implementations are written in numpy, independently of the C++
code under test, and match the HuggingFace Llama conventions exactly
(RMSNorm eps placement, split-half RoPE, SiLU gating). Output is a C++
header consumed by tests/test_ops.cpp.

Regenerate with:  python3 tools/gen_golden.py > tests/golden.h
"""
import numpy as np

rng = np.random.default_rng(0xC01D)  # fixed seed: goldens are stable

out = []
def flit(v):
    s = f"{v:.9g}"
    if "." not in s and "e" not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f"

def emit(name, arr):
    a = np.asarray(arr, dtype=np.float64).ravel()
    vals = ", ".join(flit(v) for v in a)
    out.append(f"inline constexpr std::array<float, {a.size}> {name} {{ {vals} }};")

def emit_int(name, v):
    out.append(f"inline constexpr int {name} = {int(v)};")

# ---------------------------------------------------------------- rmsnorm
D = 8
EPS = 1e-5
x = rng.standard_normal(D)
w = rng.standard_normal(D)
ref = x / np.sqrt(np.mean(x * x) + EPS) * w
emit("RMSNORM_X", x); emit("RMSNORM_W", w); emit("RMSNORM_OUT", ref)
emit_int("RMSNORM_DIM", D)

# ---------------------------------------------------------------- matvec
R, C = 3, 4
W = rng.standard_normal((R, C))
v = rng.standard_normal(C)
emit("MATVEC_W", W); emit("MATVEC_X", v); emit("MATVEC_OUT", W @ v)
emit_int("MATVEC_ROWS", R); emit_int("MATVEC_COLS", C)

# ---------------------------------------------------------------- rope
# HuggingFace Llama convention: split-half (rotate_half), NOT interleaved.
HD, POS, BASE = 8, 5, 10000.0
NQ, NKV = 2, 1

def rope_ref(vec, pos, hd, base):
    half = hd // 2
    inv_freq = base ** (-np.arange(half) * 2.0 / hd)
    ang = pos * inv_freq
    cos = np.concatenate([np.cos(ang), np.cos(ang)])
    sin = np.concatenate([np.sin(ang), np.sin(ang)])
    rot = np.concatenate([-vec[half:], vec[:half]])
    return vec * cos + rot * sin

q = rng.standard_normal(NQ * HD)
k = rng.standard_normal(NKV * HD)
q_out = np.concatenate([rope_ref(q[h*HD:(h+1)*HD], POS, HD, BASE) for h in range(NQ)])
k_out = np.concatenate([rope_ref(k[h*HD:(h+1)*HD], POS, HD, BASE) for h in range(NKV)])
emit("ROPE_Q_IN", q); emit("ROPE_K_IN", k)
emit("ROPE_Q_OUT", q_out); emit("ROPE_K_OUT", k_out)
emit_int("ROPE_HEAD_DIM", HD); emit_int("ROPE_POS", POS)
emit_int("ROPE_NQ", NQ); emit_int("ROPE_NKV", NKV)
out.append(f"inline constexpr float ROPE_BASE = {BASE}f;")

# ---------------------------------------------------------------- softmax
# Includes a huge value: naive exp() overflows, max-subtraction survives.
s = np.array([1000.0, 999.0, 0.0, -5.0, 998.0])
e = np.exp(s - s.max())
emit("SOFTMAX_X", s); emit("SOFTMAX_OUT", e / e.sum())
emit_int("SOFTMAX_N", s.size)

# ---------------------------------------------------------------- silu_mul
N = 6
g = rng.standard_normal(N) * 3
u = rng.standard_normal(N)
emit("SILU_GATE", g); emit("SILU_UP", u)
emit("SILU_OUT", (g / (1.0 + np.exp(-g))) * u)
emit_int("SILU_N", N)

# ---------------------------------------------------------------- argmax (tie)
a = np.array([1.0, 7.5, 3.0, 7.5, -2.0])
emit("ARGMAX_X", a); emit_int("ARGMAX_N", a.size)
emit_int("ARGMAX_EXPECT", 1)  # ties resolve to the lowest index

# ------------------------------------------------- attention (integration)
# One query head over a 3-entry KV cache: the composition test that proves
# matvec + softmax assemble into working attention before any weights exist.
T, AD = 3, 4
K = rng.standard_normal((T, AD))
V = rng.standard_normal((T, AD))
qa = rng.standard_normal(AD)
sc = (K @ qa) / np.sqrt(AD)
p = np.exp(sc - sc.max()); p /= p.sum()
emit("ATTN_Q", qa); emit("ATTN_K", K); emit("ATTN_V", V)
emit("ATTN_OUT", p @ V)
emit_int("ATTN_T", T); emit_int("ATTN_HEAD_DIM", AD)

print("// GENERATED by tools/gen_golden.py — do not edit by hand.")
print("// Reference: numpy, HuggingFace Llama conventions. Seed 0xC01D.")
print("#pragma once")
print("#include <array>")
print("namespace golden {")
print("\n".join(out))
print("}  // namespace golden")
